# Generated by Django 6.0 on 2025-12-25 06:59

import apps.tasks.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_number', models.CharField(db_index=True, editable=False, help_text='Auto-generated: TASK-YYYYMMDD-XXXX', max_length=20, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('task_type', models.CharField(choices=[('personal', 'Personal'), ('delegated', 'Delegated')], editable=False, help_text='Auto-set: personal if assignee==creator, else delegated', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('verified', 'Verified'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=15)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], db_index=True, default='medium', max_length=10)),
                ('deadline', models.DateTimeField(blank=True, db_index=True, help_text='Date and time (IST) when task is due', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('deadline_reminder_sent', models.BooleanField(default=False, help_text='24-hour deadline reminder sent')),
                ('first_overdue_email_sent', models.BooleanField(default=False, help_text='First overdue notification sent')),
                ('escalated_to_sm2_at', models.DateTimeField(blank=True, help_text='72-hour escalation to Senior Manager 2', null=True)),
                ('escalated_to_sm1_at', models.DateTimeField(blank=True, help_text='120-hour escalation to Senior Manager 1', null=True)),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('email', 'Email')], default='manual', max_length=10)),
                ('source_reference', models.CharField(blank=True, help_text='Email ID reference for Phase 2', max_length=255, null=True)),
                ('assignee', models.ForeignKey(help_text='User assigned to complete this task', on_delete=django.db.models.deletion.PROTECT, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL)),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_tasks', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(help_text='User who created this task', on_delete=django.db.models.deletion.PROTECT, related_name='created_tasks', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(help_text='Auto-populated from assignee', on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='departments.department')),
            ],
            options={
                'verbose_name': 'task',
                'verbose_name_plural': 'tasks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='task_comments', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='tasks.task')),
            ],
            options={
                'verbose_name': 'comment',
                'verbose_name_plural': 'comments',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=apps.tasks.models.attachment_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'xls', 'xlsx', 'png', 'jpg', 'jpeg', 'txt'])])),
                ('filename', models.CharField(help_text='Original filename', max_length=255)),
                ('file_size', models.PositiveIntegerField(help_text='File size in bytes')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_attachments', to=settings.AUTH_USER_MODEL)),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='attachment', to='tasks.task')),
            ],
            options={
                'verbose_name': 'attachment',
                'verbose_name_plural': 'attachments',
            },
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['status', 'assignee'], name='tasks_task_status_a6a8c8_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['status', 'created_by'], name='tasks_task_status_74c5ee_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['deadline', 'status'], name='tasks_task_deadlin_968687_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['department', 'status'], name='tasks_task_departm_22225e_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['reference_number'], name='tasks_task_referen_9b504a_idx'),
        ),
    ]
