# Generated by Django 6.0 on 2025-12-25 06:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tasks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('status_changed', 'Status Changed'), ('reassigned', 'Reassigned'), ('commented', 'Commented'), ('attachment_added', 'Attachment Added'), ('attachment_replaced', 'Attachment Replaced'), ('cancelled', 'Cancelled'), ('verified', 'Verified')], db_index=True, max_length=20)),
                ('description', models.TextField(help_text='Human-readable description of the change')),
                ('field_name', models.CharField(blank=True, help_text='Name of the field that was changed', max_length=50, null=True)),
                ('old_value', models.TextField(blank=True, help_text='Previous value (for field changes)', null=True)),
                ('new_value', models.TextField(blank=True, help_text='New value (for field changes)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='tasks.task')),
                ('user', models.ForeignKey(help_text='User who performed the action', on_delete=django.db.models.deletion.PROTECT, related_name='task_activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'task activity',
                'verbose_name_plural': 'task activities',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['task', '-created_at'], name='activity_lo_task_id_0f0c32_idx'), models.Index(fields=['user', '-created_at'], name='activity_lo_user_id_9b54b4_idx'), models.Index(fields=['action_type', '-created_at'], name='activity_lo_action__c67b98_idx')],
            },
        ),
    ]
